Log a warning when signal is already registered
hemerajs/fastify-graceful-shutdown pull request #46
Opened 2024-07-27 14:08 UTC by lboquillon

As discussed on #36: a warn is logged rather than throwing an error.

2024-08-08 09:02 UTC, lboquillon commented
Hi @StarpTech,
did you have the chance to look at it?
Thanks!

2024-08-09 08:45 UTC, StarpTech requested changes

2024-08-09 08:45 UTC, StarpTech commented on index.js
> +      logger.warn(`${signal} handler was already registered. Consider using fastify.gracefulShutdown`)
Please change it to `Consider using fastify.gracefulShutdown to ensure a controlled shutdown`

2024-08-09 12:05 UTC, lboquillon commented
@StarpTech done!

2024-08-09 12:52 UTC, StarpTech approved these changes
LGTM

2024-08-09 12:54 UTC, merged

2024-09-05 08:44 UTC, lboquillon commented
Hi @StarpTech,
any chance of release a new version with this change? I can do any work needed.

2025-07-31 09:07 UTC, kibertoad commented
@StarpTech Can you please either release a new version, or give me npm publish permissions (I'm already a member of core fastify plugins group, btw), so that I could do it? It's been a while, and this was a very useful change.